//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Artist { get; set; }
        public string Name { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Label { get; set; }
        public int Quantity { get; set; }
        public int TypeId { get; set; }
    
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
